### ISSUE TITLE
Firefox does not load the call with error: platform doesn't support "speaker" as target

### ISSUE THREAD

**Issue by sparkplug0025** [signalwire/browser-videoconf-full-react#9]
![image](https://user-images.githubusercontent.com/79721020/162356424-69623f68-1a97-4d06-81b1-f8baf6989172.png)

I receive this error when testing with Firefox: Error: The platform doesn't support "speaker" as target/s, which means it's not possible to watch for changes on those devices.

And then the call does not load.

Maybe it's related to #8, the call is not loading for the same reason, but then Firefox does a good job of reporting to us the issue, vs opera failing silently?

**Comment by danieleds** [comment]
@sparkplug0025 which version of Firefox are you testing this on? Firefox doesn't support "speaker" targets, but this shouldn't stop you from joining the call (it just means you can't choose your preferred speaker).

Are you using the exact same code from our master branch? Could it be that you have some additional code after the initialization of `speakerChangeWatcher`, so that when it throws it gets skipped? If so, you can safely wrap the following code from `components/Video.js` into a try/catch:

https://github.com/signalwire/browser-videoconf-full-react/blob/master/video/src/components/Video.js#L95-L101

If instead you are using the exact same code, it may be a problem with permissions. Would you mind sharing the full console output?
